// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $auth from "./routes/auth.tsx";
import * as $client_id_ from "./routes/client/[id].tsx";
import * as $client_home from "./routes/client/home.tsx";
import * as $client_new from "./routes/client/new.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $CreateEmail from "./islands/CreateEmail.tsx";
import * as $auth_1 from "./islands/auth.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/auth.tsx": $auth,
    "./routes/client/[id].tsx": $client_id_,
    "./routes/client/home.tsx": $client_home,
    "./routes/client/new.tsx": $client_new,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/CreateEmail.tsx": $CreateEmail,
    "./islands/auth.tsx": $auth_1,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
